name: Push modifs sur serveur

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - run: |
        git -C /var/www/jaxnel.top/html/projet1nouvellestechno pull origin main
