name: Push modifs sur serveur

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - run: |
        cd
        cd /var/www/jaxnel.top/html/projet1nouvellestechno
        git pull origin main
